using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Car_Agency_Management.Data;
using System.Collections.Generic;
using System.Linq;

namespace Car_Agency_Management.Pages
{
    public class AddCarModel : PageModel
    {
        private readonly DB _db;

        public AddCarModel()
        {
            _db = new DB();
        }

        [BindProperty]
        public string CarId { get; set; } = "";

        [BindProperty]
        public string CarName { get; set; } = "";

        [BindProperty]
        public string Brand { get; set; } = "";

        [BindProperty]
        public string Year { get; set; } = "";

        [BindProperty]
        public string Price { get; set; } = "";

        [BindProperty]
        public string MainImage { get; set; } = "";

        [BindProperty]
        public List<string> Images { get; set; } = new List<string>();

        [BindProperty]
        public string Transmission { get; set; } = "";

        [BindProperty]
        public string FuelType { get; set; } = "";

        [BindProperty]
        public string Engine { get; set; } = "";

        [BindProperty]
        public string Seats { get; set; } = "";

        [BindProperty]
        public string Color { get; set; } = "";

        [BindProperty]
        public string Mileage { get; set; } = "";

        [BindProperty]
        public List<string> Features { get; set; } = new List<string>();

        [BindProperty]
        public string MinDeposit { get; set; } = "";

        [BindProperty]
        public string MonthlyInstallment { get; set; } = "";

        [BindProperty]
        public string Description { get; set; } = "";

        public bool IsEditMode => !string.IsNullOrEmpty(CarId);

        [BindProperty]
        public string FeaturesString { get; set; } = "";

        public void OnGet(string? carId)
        {
            if (!string.IsNullOrEmpty(carId))
            {
                CarId = carId;
                LoadCarData(carId);
            }
        }

        public IActionResult OnPost()
        {
            // CarId is optional for new cars (generated by DB or logic)
            ModelState.Remove("CarId");

            if (!ModelState.IsValid)
            {
                return Page();
            }

            // Process features from comma-separated string
            if (!string.IsNullOrEmpty(FeaturesString))
            {
                Features = FeaturesString.Split(',', StringSplitOptions.RemoveEmptyEntries)
                    .Select(f => f.Trim())
                    .Where(f => !string.IsNullOrEmpty(f))
                    .ToList();
            }
            else
            {
                Features = new List<string>();
            }

            // Process images array
            Images = new List<string>();
            foreach (var key in Request.Form.Keys.Where(k => k.StartsWith("Images[")))
            {
                var imageUrl = Request.Form[key].ToString();
                if (!string.IsNullOrEmpty(imageUrl))
                {
                    Images.Add(imageUrl);
                }
            }

            // Create CarDetails object
            var carDetails = new CarDetails
            {
                CarId = CarId,
                CarName = CarName,
                Brand = Brand,
                Year = Year,
                Price = Price,
                MainImage = MainImage,
                Transmission = Transmission,
                FuelType = FuelType,
                Engine = Engine,
                Seats = Seats,
                Color = Color,
                Mileage = Mileage,
                MinDeposit = MinDeposit,
                MonthlyInstallment = MonthlyInstallment,
                Description = Description
            };

            string resultId = CarId;

            if (IsEditMode)
            {
                // Update implementation
                bool updated = _db.UpdateCarDetails(carDetails);
                if (!updated)
                {
                    ModelState.AddModelError("", "Failed to update car details in database.");
                    return Page();
                }

                if (updated)
                {
                    // Update features
                    _db.DeleteCarFeatures(CarId);
                    foreach (var feature in Features)
                    {
                        _db.InsertCarFeature(CarId, feature);
                    }

                    // Update images
                    _db.DeleteCarImages(CarId);
                    foreach (var img in Images)
                    {
                        _db.InsertCarImage(CarId, img);
                    }
                }
            }
            else
            {
                // Insert implementation
                resultId = _db.AddCar(carDetails);
                
                if (string.IsNullOrEmpty(resultId))
                {
                    ModelState.AddModelError("", "Failed to add car to database.");
                    return Page();
                }

                if (!string.IsNullOrEmpty(resultId))
                {
                    // Insert features
                    foreach (var feature in Features)
                    {
                        _db.InsertCarFeature(resultId, feature);
                    }

                    // Insert images
                    foreach (var img in Images)
                    {
                        _db.InsertCarImage(resultId, img);
                    }
                }
            }

            return RedirectToPage("/Car-gallery");
        }

        private void LoadCarData(string carId)
        {
            var carData = _db.GetCarDetails(carId);

            if (carData != null)
            {
                CarName = carData.CarName;
                Brand = carData.Brand;
                Year = carData.Year;
                Price = carData.Price;
                MainImage = carData.MainImage;
                Transmission = carData.Transmission;
                FuelType = carData.FuelType;
                Engine = carData.Engine;
                Seats = carData.Seats;
                Color = carData.Color;
                Mileage = carData.Mileage;
                MinDeposit = carData.MinDeposit;
                MonthlyInstallment = carData.MonthlyInstallment;
                Description = carData.Description;

                // Parse ID for methods that require int
                int.TryParse(carId, out int idInt);

                // Load features
                Features = _db.GetCarFeaturesById(idInt);
                if (Features != null)
                {
                    FeaturesString = string.Join(", ", Features);
                }

                // Load images
                Images = _db.GetCarImagesById(idInt);
            }
        }
    }
}

